const db = require('./connection');
const { Member, Movies, Merch } = require('../models');

db.once('open', async () => {
  await seed();
});

async function seed() {
  const members = await db.members.insertMany([
    {
      username: 'AlisonDilfer',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('03/02/2021'),
      leftIn: null,
      firstPickedMovie: 'House of Gucci',
      lastPickedMovie: 'The Hunger',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person', '5-time Picker+' ],
      currentRSVP: '',
      socials: [ 'Facebook', 'BlueSky', 'LetterBoxd' ]
    },
    {
      username: 'AmyUnoShafer',
      birthday: new Date('12/05/1986'),
      isActive: false,
      roles: [ 'admin', 'member' ],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstPickedMovie: "World's Greatest Dad",
      lastPickedMovie: 'Jawbreaker',
      favoriteMovies: [ 'Ed Wood', 'The Birdcage', 'The Producers(1967)', 'Eighth Grade', "Wayne's World", 'The Rocky Horror Picture Show', 'American Movie' ],
      memberStats: [ 'Founding Member', 'Admin', 'Cat Person', '10-time Picker+' ],
      currentRSVP: 'Coming!',
      socials: [ 'BlueSky', 'Facebook', 'Instagram', 'LetterBoxd', 'TikTok' ]
    },
    {
      username: 'DaveMcManus',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('08/17/2022'),
      leftIn: null,
      firstPickedMovie: null,
      lastPickedMovie: null,
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook', 'YouTube', 'X' ]
    },
    {
      username: 'DawnFallik',
      birthday: null,
      isActive: false,
      roles: ['member'],
      memberSince: new Date('06/10/2021'),
      leftIn: new Date('07/01/2022'),
      firstPickedMovie: 'The House Bunny',
      lastPickedMovie: 'FYRE: The Greatest Party That Never Happened',
      favoriteMovies: [ ],
      memberStats: [ '5-time Picker+', 'Cat Person' ],
      currentRSVP: '',
      socials: [ ]
    },
    {
      username: 'DianaD\'Orazio',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstPickedMovie: 'What Ever Happened to Baby Jane?',
      lastPickedMovie: 'The Pianist',
      favoriteMovies: [ ],
      memberStats: [ 'Founding Member', '20-time Picker', 'Bird Person' ],
      currentRSVP: 'Coming!',
      socials: [ 'Facebook' ]
    },
    {
      username: 'DougReinford',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('04/07/2025'),
      leftIn: null,
      firstPickedMovie: 'Tsotsi',
      lastPickedMovie: null,
      favoriteMovies: [ ],
      memberStats: [ 'New Member' ],
      currentRSVP: 'Coming',
      socials: [ 'Facebook', 'Flickr' ]
    },
    {
      username: 'ErikKirby',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('05/06/2021'),
      leftIn: null,
      firstPickedMovie: 'City Slickers',
      lastPickedMovie: 'American Graffiti',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person', 'Dog Person' ],
      currentRSVP: null,
      socials: [ ]
    },
    {
      username: 'JohnLenin',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('04/22/2025'),
      leftIn: null,
      firstPickedMovie: 'Take Me Home Tonight',
      lastPickedMovie: 'Take Me Home Tonight',
      favoriteMovies: [],
      memberStats: ['New Member'],
      currentRSVP: 'Not Coming.',
      socials: [ 'Facebook', 'Instagram', 'LetterBoxd' ]
    },
    {
      username: 'JenniferO\'Shea',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('01/05/2022'),
      leftIn: new Date('01/26/2022'),
      firstPickedMovie: 'Waking Ned Devine',
      lastPickedMovie: 'Waking Ned Devine',
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook', 'TikTok' ]
    },
    {
      username: 'JohannaWainscott',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('06/10/2021'),
      leftIn: new Date('07/01/2022'),
      firstPickedMovie: 'The Adventures of Walter Mitty',
      lastPickedMovie: 'The Adventures of Walter Mitty',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person' ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'JohnCecilPrice',
      birthday: null,
      isActive: false,
      roles: ['member'],
      memberSince: new Date('10/01/2020'),
      leftIn: new Date('07/10/2021'),
      firstPickedMovie: 'The Swimmer',
      lastPickedMovie: 'Desperately Seeking Susan',
      favoriteMovies: [ ],
      memberStats: [ 'Founding Member', 'Cat Person', '5-time Picker' ],
      currentRSVP: null,
      socials: [ 'Facebook', 'Twitter' ]
    },
    {
      username: 'JoshBowie',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('05/29/2024'),
      leftIn: null,
      firstPickedMovie: 'The Man Who Fell To Earth',
      lastPickedMovie: 'The Man Who Fell To Earth',
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'JuliaGuest',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('01/15/2021'),
      leftIn: new Date('04/29/2021'),
      firstPickedMovie: 'Best in Show',
      lastPickedMovie: "Romy and Michele's High School Union",
      favoriteMovies: [ ],
      memberStats: [ 'Plant Person' ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'KellyKinzey',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('01/26/2022'),
      leftIn: new Date('01/11/2023'),
      firstPickedMovie: 'To Wong Foo, Thanks for Everything! Julie Newman',
      lastPickedMovie: 'My Policeman',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person', 'Parent' ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'LaurenGervasio',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('06/10/2021'),
      leftIn: new Date('11/24/2021'),
      firstPickedMovie: 'The Greatest Showman',
      lastPickedMovie: 'The Princess Bride',
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'ReynaHowkins',
      birthday: null,
      isActive: true,
      roles: ['member'],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstPickedMovie: 'Drugstore Cowboy',
      lastPickedMovie: 'The Ice Storm',
      favoriteMovies: [],
      memberStats: [ 'Founding Member', '10-time Picker+', 'Dog Person' ],
      currentRSVP: 'Not Coming.',
      socials: [ 'Facebook', 'Instagram', 'Website' ]
    },
    {
      username: 'RuthSchanbacher',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('10/06/2021'),
      leftIn: null,
      firstPickedMovie: 'The Adventures of Baron Munchausen',
      lastPickedMovie: 'Repo Man',
      favoriteMovies: [ ],
      memberStats: [ 'Founding Member', '5-time Picker+', 'Bird Person', 'Parent' ],
      currentRSVP: 'Not Coming.',
      socials: [ 'Facebook', 'Instagram', 'Website' ]
    }
  ]);

  const movies = await db.movies.insertMany([
    // Season 1
    {
     movieTitle: 'The Swimmer',
     movieReleaseYear: 1968,
     genre: [ 'Drama' ],
     rating: 'PG',
     runtime: '1hr 35m', 
     director: [ 'Frank Perry' ],
     writer: [ 'Eleanor Perry' ],
     cast: [ 'Burt Lancaster' , 'Janet Landgard' , 'Janice Rule' , 'Joan Rivers' ],
     accolades: [ 'satellite award overall blu-ray/DVD winner 2015' ], 
     releaseDate: new Date('05/15/1968') , 
     tags: [ 'cult classic' , 'psychological drama' , 'surreal' , 'experimental' , 'satire' , 'allegorical' , 'midlife crisis' , 'suburbia' , 'existentialism' , 'american dream' , 'one-day narrative' , 'john cheever' ] ,
     viewingNumber: 1,
     dateViewed: new Date('10/01/2020'),
     picker: 'JohnCecilPrice',
     attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
     memberRating: null,
     currentlyStreaming: null,
     season: 'Season 1'
    },
     {
      movieTitle: 'World\'s Greatest Dad' ,
      movieReleaseYear: 2009,
      genre: [ 'Comedy' , 'Drama' ] ,
      rating: 'R' ,
      runtime: '1hr 39m' , 
      director: [ 'Bobcat Goldthwait' ] ,
      writer: [ 'Bobcat Goldthwait' ] ,
      cast: [ 'Robin Williams' , 'Daryl Sabara' , 'Alexie Gilmore' , 'Evan Martin' , 'Lorraine Nicholson' , 'Henry Simmons' , 'Geoff Pierson' ] ,
      accolades: [ 'deauville film festival nominee' ] , 
      releaseDate: new Date('08/21/2009'),
      tags: [ 'dark comedy' , 'satire' , 'tragicomedy' , 'indie' , 'grief' , 'internet fame' , 'creative writing' , 'high school' , 'single parent' , 'underrated' ] ,
      viewingNumber: 2,
      dateViewed: new Date('10/08/2020') ,
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ] ,
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'What Ever Happened to Baby Jane?',
      movieReleaseYear: 1962,
      genre: [ 'Drama', 'Horror' ],
      rating: 'Not Rated',
      runtime: '2h 12m',
      director: [ 'Robert Aldrich' ],
      writer: [ 'Lukas Heller' ],
      cast: [ 'Bette Davis' , 'Joan Crawford' , 'Victor Buono' ],
      accolades: [ 'oscar winner' , 'oscar nominated' , 'cannes nominated' , 'golden globe nominated'], 
      releaseDate: new Date('10/31/1062'),
      tags: [ 'black and white' , 'classic' , 'iconic' , 'cult classic' , 'campy' , 'gay cinema' , 'sibling rivalry' , 'child star' , 'infamous' , 'hagsploitation' ],
      viewingNumber: 3,
      dateViewed: new Date('10/15/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'THX 1138',
      movieReleaseYear: 1971,
      genre: ['Sci-Fi' , 'Thriller' , 'Drama' , 'Dystopian Sci-Fi' ],
      rating: 'PG',
      runtime: '1h 26m',
      director: [ 'George Lucas' ],
      writer: [ 'George Lucas' , 'Walter Murch'],
      cast: [ 'Robert Duvall' , 'Maggie McOmie' , 'Donald Pleasence' , 'Ian Wolfe' , 'Don Pedro Colley' ],
      accolades: [ 'cannes nominated' ], 
      releaseDate: new Date('03/11/1971'), 
      tags: [ 'directorial debut' , 'avant-garde' , 'arty' , 'experimental' , 'cyber punk' , 'totalitarianism' , 'drones' , 'counterculture' ],
      viewingNumber: 4,
      dateViewed: new Date('10/23/2020'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'American Werewolf in London',
      movieReleaseYear: 1981,
      genre: [ 'Body Horror' , 'Buddy Comedy' , 'Dark Comedy' , 'Supernatural Horror' , 'Werewolf Horror' , 'Comedy' , 'Horror' ],
      rating: 'R',
      runtime: '1hr 37m',
      director: [ 'John Landis' ],
      writer: [ 'John Landis' ],
      cast: [ 'David Naughton' , 'Jenny Agutter' , 'Joe Belcher' ],
      accolades: [ 'oscar-winner' ], 
      tags: [ 'werewolf' , 'horror-comedy' , 'cult classic' , 'dark comedy' ],
      releaseDate: new Date ('08/21/1981'),
      viewingNumber: 5,
      dateViewed: new Date('10/29/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Housebound',
      movieReleaseYear: 2014,
      genre: ['Horror', 'Comedy', 'Horror-Comedy', 'Mystery'],
      rating: 'Not Rated',
      runtime: '1h 47m',
      director: [ 'Gerard Johnstone' ],
      writer: [ 'Gerard Johnstone' ],
      cast: [ 'Morgana O\'Reilly' , 'Rima Te Wiata' , 'Glen-Paul Waru' ],
      accolades: [ 'toronto after dark film festival winner' ],
      releaseDate: new Date('03/10/2014'),
      tags: [ 'new zealand' , 'indie' , 'underrated' , 'twisty' ], 
      viewingNumber: 6,
      dateViewed: new Date('11/5/2020'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Drugstore Cowboy',
      movieReleaseYear: 1989,
      genre: ['Drama', 'Crime'],
      rating: 'R',
      runtime: '1hr 40m',
      director: [ 'Gus Van Sant' ],
      writer: [ 'Gus Van Sant', 'Daniel Yost' ],
      cast: [ 'Matt Dillon' , 'Kelly Lynch' , 'James Remar' , 'James LeGros' , 'Heather Graham' , 'William Burroughs' ],
      accolades: [ 'la film critics winner' , 'national society of film critics winner' , 'independent spirit award' , 'new york film critics' ], 
      releaseDate: new Date('10/06/1989'),
      tags: [ 'indie' , 'low-budget' , 'dark' , 'drugs' , 'sad' , 'amazing soundtrack' , 'cult classics' , 'arty'],
      viewingNumber: 7,
      dateViewed: new Date('11/5/2020'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'JohnCecilPrice', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'National Lampoon\'s Animal House',
      movieReleaseYear: 1978,
      genre: ['Comedy', 'Slapstick'],
      rating: 'R',
      runtime: '1hr 49m',
      director: [ 'John Landis' ],
      writer: [ 'Harold Ramis' , 'Douglas Kenney' , 'Chris Miller' ],
      cast: [ 'John Belushi' , 'Tim Matheson' , 'John Vernon' , 'Verna Bloom' , 'Thomas Hulce' , 'Donald Sutherland' , 'Karen Allen' , 'Kevin Bacon' , 'James Daughton' , 'Bruce McGill' ],
      accolades: [ 'national film registry' , 'people\'s choice award winner'], 
      releaseDate: new Date ('07/28/1978'),
      tags: [ 'crude' , 'funny' , 'college' , 'party' , 'silly' , 'amazing soundtrack' , 'iconic' ],
      viewingNumber: 8,
      dateViewed: new Date('11/19/2020'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Endless Love',
      movieReleaseYear: 1981,
      genre: [ 'Drama', 'Romance' , 'Tragedy' ],
      rating: 'R',
      runtime: '1hr 56m',
      director: [ 'Franco Zeffirelli' ],
      writer: [ 'Judith Rascoe' ],
      cast: [ 'Brooke Shields' , 'Martin Hewitt' , 'Shirley Knight' , 'Don Murray' , 'Richard Kiley' , 'Penelope Milford' , 'Beatrice Straight' ],
      accolades: [ 'oscar nominated' ], 
      releaseDate: new Date('07/17/1981'),
      tags: [ 'relationships' , 'passionate' , 'heart-break' , 'coming-of-age' ],
      viewingNumber: 8,
      dateViewed: new Date('11/25/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'The Great Dictator',
      movieReleaseYear: 1940,
      genre: [ 'Comedy', 'Drama', 'Satire', 'War', 'Parody', 'Slapstick' ],
      rating: 'G',
      runtime: '2hr 5m',
      director: [ 'Charlie Chaplin' ],
      writer: [ 'Charlie Chaplin' ],
      cast: [ 'Charlie Chaplin' , 'Paulette Goddard' , 'Jack Oakie' ],
      accolades: [ 'oscar nominated' , 'national board of review winner' , 'national film registry' ], 
      releaseDate: new Date('10/15/1940'),
      tags: [ 'iconic' , 'moving', 'funny' , 'laugh at nazis' , 'silly' , 'heroic' , 'classic' , 'black and white' ],
      viewingNumber: 10,
      dateViewed: new Date('12/01/2020'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Moonstruck',
      movieReleaseYear: 1987,
      genre: [ 'Comedy', 'Romance' ],
      rating: 'PG' ,
      runtime: '1hr 42m',
      director: [ 'Norman Jewison' ],
      writer: [ 'John Patrick Shanley' ],
      cast: [ 'Cher' , 'Nicolas Cage' , 'Vincent Gardenia' , 'Olympia Dukakis' , 'Danny Aiello' , 'Julie Bovasso' , 'John Mahoney' , 'Louis Guss' , 'Feodor Chaliapin Jr.'],
      accolades: [ 'oscar winner' , 'national film registry' , 'bafta nominee' , 'golden globe winner'], 
      releaseDate: new Date('12/18/1987'),
      tags: [ 'rom-com' , 'iconic' , 'classic' , 'chemistry' , 'laugh out loud' , 'touching' ],
      viewingNumber: 11,
      dateViewed: new Date('12/10/2020'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'The Shop Around the Corner',
      movieReleaseYear: 1940,
      genre: [ 'Comedy', 'Romance', 'Classics', 'Drama', 'Holiday' ],
      rating: 'Not Rated',
      runtime: '1hr 39m',
      director: [ 'Ernst Lubitsch' ],
      writer: [ 'Samson Raphaelson' , 'Miklós László' , 'Ben Hecht' ],
      cast: [ 'Margaret Sullavan' , 'James Stewart' , 'Frank Morgan' ],
      accolades: [ 'national film registry' , 'national board of review winner' , 'photoplay award winner' ], 
      releaseDate: new Date('01/12/1940'),
      tags: [ 'rom-com' , 'chemistry' , 'funny' , 'cute' , 'black and white' , 'classic' , 'christmas' , 'charming' ],
      viewingNumber: 12,
      dateViewed: new Date('12/17/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Trading Places',
      movieReleaseYear: 1983,
      genre: [ 'Comedy', 'Satire' ],
      rating: 'R',
      runtime: '1hr 58m',
      director: [ 'John Landis' ],
      writer: [ 'Timothy Harris' , 'Herschel Weingrod' ],
      cast: [ 'Eddie Murphy' , 'Dan Aykroyd' , 'Jamie Lee Curtis' , 'Denholm Elliott' , 'Maurice Woods' ],
      accolades: [ 'oscar nominee' , 'bafta winner' , 'golden globe nominee' , 'naacp image award winner' ], 
      releaseDate: new Date('06/08/1983'),
      tags: [ 'crude' , 'funny' , 'buddy movie' , 'commentary' , 'laugh out loud' , 'gag' , 'silly'],
      viewingNumber: 13,
      dateViewed: new Date('12/23/2020'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Grey Gardens',
      movieReleaseYear: 1975,
      genre: [ 'Documentary', 'Comedy' ] ,
      rating: 'PG',
      runtime: '1hr 35m', 
      director: ['Ellen Hovde' , 'Albert Maysles' , 'David Maysles' ],
      writer: [ ],
      cast: [ 'Edith Bouvier Beale' , 'Brooks Hyer' ],
      accolades: ['chicago international film festival nominee' , 'national film registry' , 'cinema eye honors awards winner'],
      releaseDate: new Date('09/27/2975'), 
      tags: [ 'campy' , 'iconic' , 'funny' , 'fascinating' , 'captivating' , 'gay cinema' , 'cult classic' ],
      viewingNumber: 14,
      dateViewed: new Date('12/30/2020'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     // Season 2
     {
      movieTitle: 'MadMax: Fury Road',
      movieReleaseYear: 2015,
      genre: ['Sci-Fi', 'Action' ] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 15,
      dateViewed: new Date('01/07/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Best in Show',
      movieReleaseYear: 2000,
      genre: ['Comedy', 'Mockumentary', 'Cult Classics'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 16,
      dateViewed: new Date('01/15/2021'),
      picker: 'Julia',
      attendees: [ 'Julia','ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Me Without You',
      movieReleaseYear: 2001,
      genre: ['Drama'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 17,
      dateViewed: new Date('01/21/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'After Hours',
      movieReleaseYear: 1985,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 18,
      dateViewed: new Date('01/28/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'The History of Future Folk',
      movieReleaseYear: 2012,
      genre: ['Comedy', 'Musical'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 19,
      dateViewed: new Date('02/05/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Great Expectations',
      movieReleaseYear: 1998,
      genre: ['Drama'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 20,
      dateViewed: new Date('02/12/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Casablanca',
      movieReleaseYear: 1942,
      genre: ['Drama', 'Romance', 'War'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 21,
      dateViewed: new Date('02/25/2021'),
      picker: 'Julia',
      attendees: [ 'Julia', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Roman Holiday',
      movieReleaseYear: 1953,
      genre: ['Comedy', 'Drama', 'Romance'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 22,
      dateViewed: new Date('03/04/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'Julia' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Brother from Another Planet',
      movieReleaseYear: 1984,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 23,
      dateViewed: new Date('03/18/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Woman in Gold',
      movieReleaseYear: 2015,
      genre: ['Drama'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 24,
      dateViewed: new Date('03/20/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'No Way to Treat a Lady',
      movieReleaseYear: 1968,
      genre: ['Comedy', 'Thriller'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 25,
      dateViewed: new Date('03/20/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Raising Arizona',
      movieReleaseYear: 1987,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 26,
      dateViewed: new Date('04/01/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Enchanted April',
      movieReleaseYear: 1987,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 27,
      dateViewed: new Date('04/16/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Romy and Michele\’s High School Union',
      movieReleaseYear: 1997,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 28,
      dateViewed: new Date('04/22/2021'),
      picker: 'Julia',
      attendees: [ 'Julia', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Trixie Mattel: Moving Parts',
      movieReleaseYear: 2019,
      genre: ['Documentary'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 29,
      dateViewed: new Date('04/29/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'Julia' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Strictly Ballroom',
      movieReleaseYear: 1992,
      genre: ['Drama'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 30,
      dateViewed: new Date('05/06/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Promising Young Woman',
      movieReleaseYear: 2020,
      genre: [ 'Drama' ] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 31,
      dateViewed: new Date('05/20/2021'),
      picker: 'ReynaHowkins',
      attendees: ['ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice'],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Charade',
      movieReleaseYear: 1963,
      genre: [ 'Drama' ] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 32,
      dateViewed: new Date('06/10/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'City Slickers',
      movieReleaseYear: 1991,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 33,
      dateViewed: new Date('06/24/2021'),
      picker: 'ErikEvans',
      attendees: [ 'ErikEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Desperately Seeking Susan',
      movieReleaseYear: 1985,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 34,
      dateViewed: new Date('07/01/2021'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The House Bunny',
      movieReleaseYear: 2008,
      genre: [ 'Comedy' ] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 35,
      dateViewed: new Date('07/08/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'ReynaHowkins', 'AmyUnoShafer',  'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Private Benjamin',
      movieReleaseYear: 1980,
      genre: ['Comedy'] ,
      tags: [ ],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 36,
      dateViewed: new Date('07/08/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Princess Bride',
      movieReleaseYear: 1987,
      genre: ['Comedy'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 37,
      dateViewed: new Date('07/22/2021'),
      picker: 'LaurenGervasio',
      attendees: [ 'LaurenGervasio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Muriel\'s Wedding',
      movieReleaseYear: 1994,
      genre: ['Comedy'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      viewingNumber: 38,
      dateViewed: new Date('08/12/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Only Lovers Left Alive',
      movieReleaseYear: 2013,
      genre: ['Comedy'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 39,
      dateViewed: new Date('08/19/2021'),
      picker: 'BeckyWells',
      attendees: [ 'BeckyWells' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Clue',
      movieReleaseYear: 1985,
      genre: ['Comedy'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 40,
      dateViewed: new Date('08/26/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Shining',
      movieReleaseYear: 1980,
      genre: ['Horror'] ,
      tags: ['classic', 'iconic'] ,
      viewingNumber: 41,
      dateViewed: new Date('09/02/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Hair Love',
      movieReleaseYear: 2020,
      genre: [ 'Short Fim', 'Animation' ] ,
      tags: ['oscar winner'] ,
      director: [ ],
      writer: [ ],
      cast: [],
      accolades: [], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 42,
      dateViewed: new Date('09/10/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Two Distant Strangers',
      movieReleaseYear: 2020,
      genre: [ 'Short Fim' ] ,
      tags: [ 'oscar nominated' ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 43,
      dateViewed: new Date('09/10/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Office Space',
      movieReleaseYear: 1999,
      genre: ['Comedy'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 44,
      dateViewed: new Date('09/16/2021'),
      picker: 'ErikEvans',
      attendees: [ 'ErikEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Screwed',
      movieReleaseYear: 2000,
      genre: ['Comedy'] ,
      tags: ['rip viewing'] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 44,
      dateViewed: new Date('09/22/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Baby Mama',
      movieReleaseYear: 2008,
      genre: ['Comedy'] ,
      tags: ['bubby movie'],
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 45,
      dateViewed: new Date('09/29/2021'),
      picker: 'LaurenGervasio',
      attendees: [ 'LaurenGervasio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Asenic and Old Lace',
      movieReleaseYear: 1944,
      genre: ['Comedy'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: newDate('01/01/2020') , 
      viewingNumber: 46,
      dateViewed: new Date('10/06/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Edward Scissorhands',
      movieReleaseYear: 1990,
      genre: ['Comedy', 'Halloween', 'Holiday'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: newDate('01/01/2020') , 
      viewingNumber: 47,
      dateViewed: new Date('10/13/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'What We Do In Shadows',
      movieReleaseYear: 2014,
      genre: ['Comedy', 'Halloween', 'Mockumentary'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020'),
      viewingNumber: 48, 
      dateViewed: new Date('10/20/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'DianaD\'Orazio', 'AmyUnoShafer', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Young Frankenstein',
      movieReleaseYear: 1974,
      genre: ['Comedy', 'Parody'] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 49,
      dateViewed: new Date('10/27/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Labyrinth',
      movieReleaseYear: 1986,
      genre: ['Comedy', 'Musical'] ,
      tags: [] ,
      director: [ ],
      writer: [ ],
      cast: [],
      accolades: [], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 50,
      dateViewed: new Date('11/03/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'American Graffiti',
      movieReleaseYear: 1973,
      genre: [ 'Comedy' ] ,
      tags: ['classic'] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 51,
      dateViewed: new Date('11/09/2021'),
      picker: 'ErikEvans',
      attendees: [ 'ErikEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },  
     {
      movieTitle: 'The Greatest Showman',
      movieReleaseYear: 2017,
      genre: [ 'Musical' ] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 52,
      dateViewed: new Date('11/17/2021'),
      picker: 'LaurenGervasio',
      attendees: [ 'LaurenGervasio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },  
     {
      movieTitle: 'The Adventures of Baron Munchausen',
      movieReleaseYear: 1988,
      genre: [ 'Adventure' ] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 53,
      dateViewed: new Date('11/24/2021'),
      picker: 'RuthSchanbacher',
      attendees: [ 'RuthSchanbacher', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Die Hard',
      movieReleaseYear: 1988,
      genre: [ 'Action' ] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 54,
      dateViewed: new Date('12/01/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Accidental Tourist',
      movieReleaseYear: 1988,
      genre: [ 'Action' ] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 55,
      dateViewed: new Date('11/09/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Clueless',
      movieReleaseYear: 1995,
      genre: [ 'Comedy' ] ,
      tags: [ ] ,
      director: [ ],
      writer: [ ],
      cast: [ ],
      accolades: [ ], 
      releaseDate: new Date('01/01/2020') , 
      viewingNumber: 56,
      dateViewed: new Date('12/22/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Silver Streak',
      movieReleaseYear: 1976,
      genre: [ 'Action' , 'Adventure' , 'Crime' , 'Comedy' , 'Romance' , 'Thriller' ] ,
      rating: 'PG',
      runtime: '1hr 54m',
      director: [ 'Arthur Hiller' ],
      writer: [ 'Colin Higgins' ],
      cast: [ 'Gene Wilder' , 'Richard Pryor' , 'Jill Clayburgh' ],
      accolades: [ 'oscar-nominated' , 'golden globe-nominated'], 
      releaseDate: new Date('12/08/1976') , 
      tags: [ 'mistaken identity' , 'cult classic' , 'comedy duo' ] ,
      viewingNumber: 57,
      dateViewed: new Date('12/29/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },   
     // Season 3
     {
      movieTitle: 'Tootsie',
      movieReleaseYear: 1982,
      genre: [ 'Comedy', 'Romance' ] ,
      rating: 'PG',
      runtime: '1h 56m',
      director: [ 'Sydney Pollack' ],
      writer: [ 'Larry Gelbart' , 'Murray Schisgal' ],
      cast: [ 'Dustin Hoffman' , 'Jessica Lange' , 'Teri Garr' , 'Dabney Coleman' , 'Charles Durning' , 'Geena Davis' , 'Bill Murray' ],
      accolades: [ 'oscar-winner' , 'national film registry' , 'afi'], 
      releaseDate: newDate('01/01/2020') , 
      tags: [ 'feminism' , 'gender roles' , 'drag' , 'showbiz' , 'soap opera' , 'love triangle' , 'classic' , 'social commentary' ] ,
      releaseDate: new Date('12/17/1982'),
      viewingNumber: 58,
      dateViewed: new Date('01/05/2022'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: "Season 3"
     },  
     {
      movieTitle: 'Scott Pilgrim vs the World',
      movieReleaseYear: 2010,
      genre: [ 'Comedy', 'Action' ] ,
      rating: 'PG-13',
      runtime: '1h 52m',
      director: [ 'Edgar Wright' ],
      writer: [ 'Edgar Wright' , 'Michael Bacall' , 'Byran Lee O\'Malley' ],
      cast: [ 'Michael Cera' , 'Kieran Culkin' , 'Anna Kendrick' , 'Alison Pill' , 'Aubrey Plaza' , 'Mary Elizabeth Winstead' , 'Jason Schwartzman' , 'Ellen Wong' , 'Chris Evans' , 'Brie Lawson' , 'Mae Whitman' , 'Bill Hader'],
      accolades: [ 'Lund International Fantastic Film Festival' ], 
      releaseDate: new Date('08/13/2010'), 
      tags: [ 'indie' , 'toronto' , 'graphic novel' , 'visual effects' , 'quirky' , 'cult classics' , 'coming-of-age' ] ,
      viewingNumber: 59,
      dateViewed: new Date('01/12/2022'),
      picker: 'RuthSchanbacher',
      attendees: [ 'RuthSchanbacher', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: "Season 3"
     },  
     {
      movieTitle: 'Waking Ned Devine',
      movieReleaseYear: 1998,
      genre: [ 'Comedy', 'Indie' ] ,
      rating: 'PG',
      runtime: '1h 31m',
      director: [ 'Kirk Jones' ],
      writer: [ 'Kirk Jones' ],
      cast: [ 'Ian Bannen' , 'David Kelly' , 'Fionnula Flanagan' , 'Susan Lynch' , 'James Nesbitt'],
      accolades: [ 'BAFTA-nominated' ], 
      releaseDate: new Date('11/20/1998'), 
      tags: [ 'indie' , 'heartwarming' , 'buddy movie' , 'sweet' , 'irish' , 'cult classic' , 'underrated' ] ,
      viewingNumber: 60,
      dateViewed: new Date('01/19/2022'),
      picker: 'JenniferO\'Shea',
      attendees: [ 'JenniferO\'Shea', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: "Season 3"
     },  
  ]);

  const merch = await db.merch.insertMany([
    // add your merch data here
  ]);

  console.log('Hit Play!');
}
