const db = require('./connection');
const { Member, Movies, Merch } = require('../models');

db.once('open', async () => {
  await seed();
});

async function seed() {
  const members = await db.members.insertMany([
    {
      username: 'AlisonDilfer',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('03/02/2021'),
      leftIn: null,
      firstMoviePicked: 'House of Gucci',
      mostRecentMoviePicked: 'The Hunger',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person', '5-time Picker+' ],
      currentRSVP: '',
      socials: [ 'Facebook', 'BlueSky', 'LetterBoxd' ]
    },
    {
      username: 'AmyUnoShafer',
      birthday: new Date('12/05/1986'),
      isActive: false,
      roles: [ 'admin', 'member' ],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstMoviePicked: 'World\'s Greatest Dad',
      mostRecentMoviePicked: 'Jawbreaker',
      favoriteMovies: [ 'Ed Wood', 'The Birdcage', 'The Producers(1967)', 'Eighth Grade', "Wayne's World", 'The Rocky Horror Picture Show', 'American Movie' ],
      memberStats: [ 'Founding Member', 'Admin', 'Cat Person', '10-time Picker+' ],
      currentRSVP: 'Coming!',
      socials: [ 'BlueSky', 'Facebook', 'Instagram', 'LetterBoxd', 'TikTok' ]
    },
        {
      username: 'BeckySwinton',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstMoviePicked: 'Only Lovers Left Alive',
      mostRecentMoviePicked: 'Jawbreaker',
      favoriteMovies: [ 'Ed Wood', 'The Birdcage', 'The Producers(1967)', 'Eighth Grade', "Wayne's World", 'The Rocky Horror Picture Show', 'American Movie' ],
      memberStats: [ 'Founding Member', 'Admin', 'Cat Person', '10-time Picker+' ],
      currentRSVP: 'Coming!',
      socials: [ 'BlueSky', 'Facebook', 'Instagram', 'LetterBoxd', 'TikTok' ]
    },
    {
      username: 'DaveMcManus',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('08/17/2022'),
      leftIn: null,
      firstMoviePicked: null,
      mostRecentMoviePicked: null,
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook', 'YouTube', 'X' ]
    },
    {
      username: 'DawnFallik',
      birthday: null,
      isActive: false,
      roles: ['member'],
      memberSince: new Date('06/10/2021'),
      leftIn: new Date('07/01/2022'),
      firstMoviePicked: 'The House Bunny',
      mostRecentMoviePicked: 'FYRE: The Greatest Party That Never Happened',
      favoriteMovies: [ ],
      memberStats: [ '5-time Picker+', 'Cat Person' ],
      currentRSVP: '',
      socials: [ ]
    },
    {
      username: 'DianaD\'Orazio',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstMoviePicked: 'What Ever Happened to Baby Jane?',
      mostRecentMoviePicked: 'The Pianist',
      favoriteMovies: [ ],
      memberStats: [ 'Founding Member', '20-time Picker', 'Bird Person' ],
      currentRSVP: 'Coming!',
      socials: [ 'Facebook' ]
    },
    {
      username: 'DougReinford',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('04/07/2025'),
      leftIn: null,
      firstMoviePicked: 'Tsotsi',
      mostRecentMoviePicked: null,
      favoriteMovies: [ ],
      memberStats: [ 'New Member' ],
      currentRSVP: 'Coming',
      socials: [ 'Facebook', 'Flickr' ]
    },
    {
      username: 'ErikKirby',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('05/06/2021'),
      leftIn: null,
      firstMoviePicked: 'City Slickers',
      mostRecentMoviePicked: 'American Graffiti',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person', 'Dog Person' ],
      currentRSVP: null,
      socials: [ ]
    },
    {
      username: 'JohnLenin',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('04/22/2025'),
      leftIn: null,
      firstMoviePicked: 'Take Me Home Tonight',
      mostRecentMoviePicked: 'Take Me Home Tonight',
      favoriteMovies: [],
      memberStats: ['New Member'],
      currentRSVP: 'Not Coming.',
      socials: [ 'Facebook', 'Instagram', 'LetterBoxd' ]
    },
    {
      username: 'JenniferO\'Shea',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('01/05/2022'),
      leftIn: new Date('01/26/2022'),
      firstMoviePicked: 'Waking Ned Devine',
      mostRecentMoviePicked: 'Waking Ned Devine',
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook', 'TikTok' ]
    },
    {
      username: 'JohannaWainscott',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('06/10/2021'),
      leftIn: new Date('07/01/2022'),
      firstMoviePicked: 'The Adventures of Walter Mitty',
      mostRecentMoviePicked: 'The Adventures of Walter Mitty',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person' ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'JohnCecilPrice',
      birthday: null,
      isActive: false,
      roles: ['member'],
      memberSince: new Date('10/01/2020'),
      leftIn: new Date('07/10/2021'),
      firstMoviePicked: 'The Swimmer',
      mostRecentMoviePicked: 'Desperately Seeking Susan',
      favoriteMovies: [ ],
      memberStats: [ 'Founding Member', 'Cat Person', '5-time Picker' ],
      currentRSVP: null,
      socials: [ 'Facebook', 'Twitter' ]
    },
    {
      username: 'JoshBowie',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('05/29/2024'),
      leftIn: null,
      firstMoviePicked: 'The Man Who Fell To Earth',
      mostRecentMoviePicked: 'The Man Who Fell To Earth',
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'JuliaFleck',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('01/15/2021'),
      leftIn: new Date('04/29/2021'),
      firstMoviePicked: 'Best in Show',
      mostRecentMoviePicked: "Romy and Michele's High School Union",
      favoriteMovies: [ ],
      memberStats: [ 'Plant Person' ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'KellyKinzey',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('01/26/2022'),
      leftIn: new Date('01/11/2023'),
      firstMoviePicked: 'To Wong Foo, Thanks for Everything! Julie Newman',
      mostRecentMoviePicked: 'My Policeman',
      favoriteMovies: [ ],
      memberStats: [ 'Cat Person', 'Parent' ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'LaurenGervasio',
      birthday: null,
      isActive: false,
      roles: [ 'member' ],
      memberSince: new Date('06/10/2021'),
      leftIn: new Date('11/24/2021'),
      firstMoviePicked: 'The Greatest Showman',
      mostRecentMoviePicked: 'The Princess Bride',
      favoriteMovies: [ ],
      memberStats: [ ],
      currentRSVP: '',
      socials: [ 'Facebook' ]
    },
    {
      username: 'ReynaHowkins',
      birthday: null,
      isActive: true,
      roles: ['member'],
      memberSince: new Date('10/01/2020'),
      leftIn: null,
      firstMoviePicked: 'Drugstore Cowboy',
      mostRecentMoviePicked: 'The Ice Storm',
      favoriteMovies: [],
      memberStats: [ 'Founding Member', '10-time Picker+', 'Dog Person' ],
      currentRSVP: 'Not Coming.',
      socials: [ 'Facebook', 'Instagram', 'Website' ]
    },
    {
      username: 'RuthSchanbacher',
      birthday: null,
      isActive: true,
      roles: [ 'member' ],
      memberSince: new Date('10/06/2021'),
      leftIn: null,
      firstMoviePicked: 'The Adventures of Baron Munchausen',
      mostRecentMoviePicked: 'Repo Man',
      favoriteMovies: [ ],
      memberStats: [ 'Founding Member', '5-time Picker+', 'Bird Person', 'Parent' ],
      currentRSVP: 'Not Coming.',
      socials: [ 'Facebook', 'Instagram', 'Website' ]
    }
  ]);

  const movies = await db.movies.insertMany([
    // Season 1
    {
     movieTitle: 'The Swimmer',
     movieReleaseYear: 1968,
     genre: [ 'Drama' ],
     rating: 'PG',
     runtime: '1hr 35m', 
     director: [ 'Frank Perry' ],
     writer: [ 'Eleanor Perry' ],
     cast: [ 'Burt Lancaster' , 'Janet Landgard' , 'Janice Rule' , 'Joan Rivers' ],
     accolades: [ 'Satellite Award Overall Blu-Ray/DVD Winner 2015' ], 
     releaseDate: new Date('05/15/1968') , 
     tags: [ 'cult classic' , 'psychological drama' , 'surreal' , 'experimental' , 'satire' , 'allegorical' , 'midlife crisis' , 'suburbia' , 'existentialism' , 'american dream' , 'one-day narrative' , 'john cheever' ] ,
     viewingNumber: 1,
     dateViewed: new Date('10/01/2020'),
     picker: 'JohnCecilPrice',
     attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
     memberRating: null,
     currentlyStreaming: null,
     season: 'Season 1'
    },
     {
      movieTitle: 'World\'s Greatest Dad' ,
      movieReleaseYear: 2009,
      genre: [ 'Comedy' , 'Drama' ] ,
      rating: 'R' ,
      runtime: '1hr 39m' , 
      director: [ 'Bobcat Goldthwait' ] ,
      writer: [ 'Bobcat Goldthwait' ] ,
      cast: [ 'Robin Williams' , 'Daryl Sabara' , 'Alexie Gilmore' , 'Evan Martin' , 'Lorraine Nicholson' , 'Henry Simmons' , 'Geoff Pierson' ] ,
      accolades: [ 'Deauville Film Festival Nominee' ] , 
      releaseDate: new Date('08/21/2009'),
      tags: [ 'dark comedy' , 'satire' , 'tragicomedy' , 'indie' , 'grief' , 'internet fame' , 'creative writing' , 'high school' , 'single parent' , 'underrated' ] ,
      viewingNumber: 2,
      dateViewed: new Date('10/08/2020') ,
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ] ,
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'What Ever Happened to Baby Jane?',
      movieReleaseYear: 1962,
      genre: [ 'Drama', 'Horror' ],
      rating: 'Not Rated',
      runtime: '2hr 12m',
      director: [ 'Robert Aldrich' ],
      writer: [ 'Lukas Heller' ],
      cast: [ 'Bette Davis' , 'Joan Crawford' , 'Victor Buono' ],
      accolades: [ 'Oscar Winner' , 'Oscar Jominated' , 'Cannes Nominated' , 'Golden Globe Nominated'], 
      releaseDate: new Date('10/31/1062'),
      tags: [ 'black and white' , 'classic' , 'iconic' , 'cult classic' , 'campy' , 'gay cinema' , 'sibling rivalry' , 'child star' , 'infamous' , 'hagsploitation' ],
      viewingNumber: 3,
      dateViewed: new Date('10/15/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'THX 1138',
      movieReleaseYear: 1971,
      genre: [ 'Sci-Fi' , 'Thriller' , 'Drama' , 'Dystopian Sci-Fi' ],
      rating: 'PG',
      runtime: '1hr 26m',
      director: [ 'George Lucas' ],
      writer: [ 'George Lucas' , 'Walter Murch'],
      cast: [ 'Robert Duvall' , 'Maggie McOmie' , 'Donald Pleasence' , 'Ian Wolfe' , 'Don Pedro Colley' ],
      accolades: [ 'Cannes Nominated' ], 
      releaseDate: new Date('03/11/1971'), 
      tags: [ 'directorial debut' , 'avant-garde' , 'arty' , 'experimental' , 'cyber punk' , 'totalitarianism' , 'drones' , 'counterculture' ],
      viewingNumber: 4,
      dateViewed: new Date('10/23/2020'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'American Werewolf in London',
      movieReleaseYear: 1981,
      genre: [ 'Body Horror' , 'Buddy Comedy' , 'Dark Comedy' , 'Supernatural Horror' , 'Werewolf Horror' , 'Comedy' , 'Horror' ],
      rating: 'R',
      runtime: '1hr 37m',
      director: [ 'John Landis' ],
      writer: [ 'John Landis' ],
      cast: [ 'David Naughton' , 'Jenny Agutter' , 'Joe Belcher' ],
      accolades: [ 'Oscar Winner' ], 
      tags: [ 'werewolf' , 'horror-comedy' , 'cult classic' , 'dark comedy' ],
      releaseDate: new Date ('08/21/1981'),
      viewingNumber: 5,
      dateViewed: new Date('10/29/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Housebound',
      movieReleaseYear: 2014,
      genre: [ 'Horror', 'Comedy', 'Horror-Comedy', 'Mystery' ],
      rating: 'Not Rated',
      runtime: '1hr 47m',
      director: [ 'Gerard Johnstone' ],
      writer: [ 'Gerard Johnstone' ],
      cast: [ 'Morgana O\'Reilly' , 'Rima Te Wiata' , 'Glen-Paul Waru' ],
      accolades: [ 'Toronto After Dark Film Festival Winner' ],
      releaseDate: new Date('03/10/2014'),
      tags: [ 'new zealand' , 'indie' , 'underrated' , 'twisty' ], 
      viewingNumber: 6,
      dateViewed: new Date('11/5/2020'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Drugstore Cowboy',
      movieReleaseYear: 1989,
      genre: [ 'Drama', 'Crime' ],
      rating: 'R',
      runtime: '1hr 40m',
      director: [ 'Gus Van Sant' ],
      writer: [ 'Gus Van Sant', 'Daniel Yost' ],
      cast: [ 'Matt Dillon' , 'Kelly Lynch' , 'James Remar' , 'James LeGros' , 'Heather Graham' , 'William Burroughs' ],
      accolades: [ 'la film critics winner' , 'national society of film critics winner' , 'independent spirit award' , 'new york film critics' ], 
      releaseDate: new Date('10/06/1989'),
      tags: [ 'indie' , 'low-budget' , 'dark' , 'drugs' , 'sad' , 'amazing soundtrack' , 'cult classics' , 'arty'],
      viewingNumber: 7,
      dateViewed: new Date('11/5/2020'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'JohnCecilPrice', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'National Lampoon\'s Animal House',
      movieReleaseYear: 1978,
      genre: ['Comedy', 'Slapstick'],
      rating: 'R',
      runtime: '1hr 49m',
      director: [ 'John Landis' ],
      writer: [ 'Harold Ramis' , 'Douglas Kenney' , 'Chris Miller' ],
      cast: [ 'John Belushi' , 'Tim Matheson' , 'John Vernon' , 'Verna Bloom' , 'Thomas Hulce' , 'Donald Sutherland' , 'Karen Allen' , 'Kevin Bacon' , 'James Daughton' , 'Bruce McGill' ],
      accolades: [ 'national film registry' , 'people\'s choice award winner'], 
      releaseDate: new Date ('07/28/1978'),
      tags: [ 'crude' , 'funny' , 'college' , 'party' , 'silly' , 'amazing soundtrack' , 'iconic' ],
      viewingNumber: 8,
      dateViewed: new Date('11/19/2020'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Endless Love',
      movieReleaseYear: 1981,
      genre: [ 'Drama', 'Romance' , 'Tragedy' ],
      rating: 'R',
      runtime: '1hr 56m',
      director: [ 'Franco Zeffirelli' ],
      writer: [ 'Judith Rascoe' ],
      cast: [ 'Brooke Shields' , 'Martin Hewitt' , 'Shirley Knight' , 'Don Murray' , 'Richard Kiley' , 'Penelope Milford' , 'Beatrice Straight' ],
      accolades: [ 'oscar nominated' ], 
      releaseDate: new Date('07/17/1981'),
      tags: [ 'relationships' , 'passionate' , 'heart-break' , 'coming-of-age' ],
      viewingNumber: 8,
      dateViewed: new Date('11/25/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'The Great Dictator',
      movieReleaseYear: 1940,
      genre: [ 'Comedy', 'Drama', 'Satire', 'War', 'Parody', 'Slapstick' ],
      rating: 'G',
      runtime: '2hr 5m',
      director: [ 'Charlie Chaplin' ],
      writer: [ 'Charlie Chaplin' ],
      cast: [ 'Charlie Chaplin' , 'Paulette Goddard' , 'Jack Oakie' ],
      accolades: [ 'oscar nominated' , 'national board of review winner' , 'national film registry' ], 
      releaseDate: new Date('10/15/1940'),
      tags: [ 'iconic' , 'moving', 'funny' , 'laugh at nazis' , 'silly' , 'heroic' , 'classic' , 'black and white' ],
      viewingNumber: 10,
      dateViewed: new Date('12/01/2020'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Moonstruck',
      movieReleaseYear: 1987,
      genre: [ 'Comedy', 'Romance' ],
      rating: 'PG' ,
      runtime: '1hr 42m',
      director: [ 'Norman Jewison' ],
      writer: [ 'John Patrick Shanley' ],
      cast: [ 'Cher' , 'Nicolas Cage' , 'Vincent Gardenia' , 'Olympia Dukakis' , 'Danny Aiello' , 'Julie Bovasso' , 'John Mahoney' , 'Louis Guss' , 'Feodor Chaliapin Jr.'],
      accolades: [ 'oscar winner' , 'national film registry' , 'bafta nominee' , 'golden globe winner'], 
      releaseDate: new Date('12/18/1987'),
      tags: [ 'rom-com' , 'iconic' , 'classic' , 'chemistry' , 'laugh out loud' , 'touching' ],
      viewingNumber: 11,
      dateViewed: new Date('12/10/2020'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'The Shop Around the Corner',
      movieReleaseYear: 1940,
      genre: [ 'Comedy', 'Romance', 'Classics', 'Drama', 'Holiday' ],
      rating: 'Not Rated',
      runtime: '1hr 39m',
      director: [ 'Ernst Lubitsch' ],
      writer: [ 'Samson Raphaelson' , 'Miklós László' , 'Ben Hecht' ],
      cast: [ 'Margaret Sullavan' , 'James Stewart' , 'Frank Morgan' ],
      accolades: [ 'national film registry' , 'national board of review winner' , 'photoplay award winner' ], 
      releaseDate: new Date('01/12/1940'),
      tags: [ 'rom-com' , 'chemistry' , 'funny' , 'cute' , 'black and white' , 'classic' , 'christmas' , 'charming' ],
      viewingNumber: 12,
      dateViewed: new Date('12/17/2020'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Trading Places',
      movieReleaseYear: 1983,
      genre: [ 'Comedy', 'Satire' ],
      rating: 'R',
      runtime: '1hr 58m',
      director: [ 'John Landis' ],
      writer: [ 'Timothy Harris' , 'Herschel Weingrod' ],
      cast: [ 'Eddie Murphy' , 'Dan Aykroyd' , 'Jamie Lee Curtis' , 'Denholm Elliott' , 'Maurice Woods' ],
      accolades: [ 'oscar nominee' , 'bafta winner' , 'golden globe nominee' , 'naacp image award winner' ], 
      releaseDate: new Date('06/08/1983'),
      tags: [ 'crude' , 'funny' , 'buddy movie' , 'commentary' , 'laugh out loud' , 'gag' , 'silly'],
      viewingNumber: 13,
      dateViewed: new Date('12/23/2020'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     {
      movieTitle: 'Grey Gardens',
      movieReleaseYear: 1975,
      genre: [ 'Documentary', 'Comedy' ] ,
      rating: 'PG',
      runtime: '1hr 35m', 
      director: ['Ellen Hovde' , 'Albert Maysles' , 'David Maysles' ],
      writer: [ ],
      cast: [ 'Edith Bouvier Beale' , 'Brooks Hyer' ],
      accolades: ['chicago international film festival nominee' , 'national film registry' , 'cinema eye honors awards winner'],
      releaseDate: new Date('09/27/2975'), 
      tags: [ 'campy' , 'iconic' , 'funny' , 'fascinating' , 'captivating' , 'gay cinema' , 'cult classic' ],
      viewingNumber: 14,
      dateViewed: new Date('12/30/2020'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 1'
     },
     // Season 2
     {
      movieTitle: 'MadMax: Fury Road',
      movieReleaseYear: 2015,
      rating: 'R',
      runtime: '2hr',
      genre: [ 'Sci-Fi', 'Action' , 'Adventure' , 'Epic' ] ,
      director: [ 'George Miller' ],
      writer: [ 'George Miller' , 'Brendan McCarthy' , 'Nick Lathouris' ],
      cast: [ 'Charlize Theron' , 'Tom Hardy' , 'Nicholas Hoult' , 'Hugh Keays-Byrne' , 'Josh Helman' , 'Nathan Jones' , 'Zoë Kravitz' , 'Rosie Alice Huntington-Whitele' ],
      accolades: [ 'oscar winner' , 'Film Critics Circle of Australia Awards' ], 
      releaseDate: new Date('05/14/2017'),
      tags: [ 'australian' , 'post-apocalytic' , 'franchise' , 'dark' , 'commentary' , 'big-budget' , 'visual effects' , 'car chase'],
      viewingNumber: 15,
      dateViewed: new Date('01/07/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Best in Show',
      movieReleaseYear: 2000,
      genre: [ 'Comedy', 'Mockumentary' ] ,
      rating: 'PG-13',
      runtime: '1hr 30m',
      director: [ 'Christopher Guest' ],
      writer: [ 'Christopher Guest' , 'Eugene Levy' ],
      cast: [ 'Christopher Guest' , 'Eugene Levy' , 'Catherine O\'Hara' , 'Parker Posey' , 'Michael Hitchcock' , 'Bob Balaban' , 'Jennifer Coolidge' , 'John Michael Higggins' , 'Jane Lynch' , 'Michael McKean' , 'Fred Willard' ],
      accolades: [ 'american comedy awards winner' , 'british comedy awards' , 'canadian comedy awards' , 'golden globes nominee' , 'national board of review winner' , 'AFI Awards - Movie of the Year' ], 
      tags: [ 'funny' , 'cult classic' , 'ensemble cast' , 'quirky' , 'laugh out loud' ],
      viewingNumber: 16,
      dateViewed: new Date('01/15/2021'),
      picker: 'JuliaFleck',
      attendees: [ 'JuliaFleck','ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Me Without You',
      movieReleaseYear: 2001,
      genre: [ 'Drama' ] ,
      rating: 'R',
      runtime: '1hr 47m',
      director: [ 'Sandra Goldbacher' ],
      writer: [ 'Sandra Goldbaucher' , 'Laurence Coriat' ],
      cast: [ 'Michelle Williams' , 'Anna Friel' , 'Kyle MacLachlan' , 'Ella Jones' , 'Young Marina' ],
      accolades: ['BAFTA Nominee' , 'Venice Film Festival' ],
      releaseDate: new Date('11/23/2001'), 
      tags: [ 'coming-of-age' , 'british' , 'low-budget' , 'indie' , 'heavy' , 'female friendships' ],
      viewingNumber: 17,
      dateViewed: new Date('01/21/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'After Hours',
      movieReleaseYear: 1985,
      genre: [ 'Comedy' , 'Thriller' , 'Crime' , 'Drama' , 'Dark Comedy' , 'Screwball Comedy' ] ,
      rating: 'R',
      runtime: '1hr 37m',
      director: [ 'Martin Scorsese' ],
      writer: [ 'Joseph Minion' ],
      cast: [ 'Griffin Dunne' , 'Rosanna Arquette' , 'Verna Bloom' , 'Tommy Chong' , 'Lida Fiorentino' , 'Teri Garr' , 'John Heard' , 'Cheech Marin' , 'Catherine O\'Hara' , 'Dick Miller' ],
      accolades: [ 'BAFTA Nominee' , 'Cannes Winner' , 'Golden Globes' ],
      releaseDate: new Date('09/13/1985'),
      tags: [ 'low-budget' , 'one-night adventures' , 'quirky' , 'bizarre' , 'funny' , 'outlandish' , 'amazing soundtrack' ], 
      viewingNumber: 18,
      dateViewed: new Date('01/28/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'The History of Future Folk',
      movieReleaseYear: 2012,
      genre: [ 'Comedy', 'Musical' , 'Sci-Fi' ] ,
      rating: 'Not Rated',
      runtime: '1hr 27m',
      director: [ 'John Mitchell' , 'Jeremy Kipp Walker' ],
      writer: [ 'John Mitchell' ],
      cast: [ 'Nils d\'Aulaire'  , 'Jay Klaitz' , 'Julie Ann Emery' , 'April Hernandez Castillo' , 'Onata Aorile' , 'Dee Snider' ],
      accolades: [ 'Film Independent Spirit Award Nominee' , 'Philadelphia Film Festival Winner (Audience Award)' , 'Austin Fantastic Fest Winner' ],
      releaseDate: null,
      tags: [ 'indie' , 'cute' , 'low-budget' , 'underrated' , 'family-friendly' , 'sweet' , 'about music' , 'different' , 'quirky' ], 
      viewingNumber: 19,
      dateViewed: new Date('02/05/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Great Expectations',
      movieReleaseYear: 1998,
      genre: [ 'Drama' , 'Romance' ] ,
      rating: 'R',
      runtime: '1hr 51m',
      director: [ 'Alfonso Cuarón' ],
      writer: [ 'Charles Dickens' , 'Mitch Glazer' ],
      cast: [ 'Gwyneth Paltrow' , 'Ethan Hawke' , 'Hank Azaria' , 'Chris Cooper' , 'Anne Bancraft' , 'Robert De Niro' , 'Josh Mostel' , 'Kim Dickens' , 'Nell Campbell' , 'Gabriel Mann' ],
      accolades: [ 'ALMA Awards Nominee' , 'Boston Society of Film Critics Awards Nominee' ],
      releaseDate: new Date('01/30/1998'),
      tags: [ 'coming-of-age' , 'remake' , 'based on a book' , 'passionate' , 'heavy'], 
      viewingNumber: 20,
      dateViewed: new Date('02/12/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Casablanca',
      movieReleaseYear: 1942,
      genre: [ 'Drama', 'Romance', 'War' ],
      rating: 'PG',
      runtime: '1hr 42m',
      director: [ 'Michael Curtiz' ],
      writer: [ 'Julius J. Epstein' , 'Philip G. Epstein' , 'Howard Koch' ],
      cast: [ 'Humphrey Bogart' , 'Ingrid Bergman' , 'Paul Henreid' , 'Claude Rains' , 'Conrad Veidt' , 'Sydney Greenstreet' , 'Pete Lorre' , 'S.Z. Sakall' ],
      accolades: [ 'Oscar Winner' , 'National Film Registry' , 'National Board of Review Winner' , 'Photoplay Winner' ],
      releaseDate: new Date('11/26/1942'),
      tags: [ 'classic' , 'must-see' , 'black and white' , 'iconic' , 'adventure' , 'human rights' , 'politics' , 'powerful' , 'fashion in film' ], 
      viewingNumber: 21,
      dateViewed: new Date('02/25/2021'),
      picker: 'JuliaFleck',
      attendees: [ 'JuliaFleck', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Roman Holiday',
      movieReleaseYear: 1953,
      genre: [ 'Comedy', 'Drama', 'Romance' ],
      rating: 'G',
      runtime: '1hr 58m',
      director: [ 'William Wyler' ],
      writer: [ 'Dalton Trumbo' , 'Ian McLellan Hunter' , 'John Dighton' ],
      cast: [ 'Aufrey Hepbrun' , 'Gregory Peck' , 'Eddie Albert' ],
      accolades: [ 'Oscar Winner' , 'BAFTA Winner' , 'Golden Globe Winner' , 'National Board of Review' , 'National Film Registry' ],
      releaseDate: new Date('08/27/1953'), 
      tags: [ 'classic' , 'must-see' , 'touching' , 'sweet' , 'travel' , 'iconic' , 'laugh out loud' , 'tearjerker' , 'fairy-tale' , 'magic' , 'perfection' , 'italy' , 'fashion in film' ],
      viewingNumber: 22,
      dateViewed: new Date('03/04/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'JuliaFleck' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Brother from Another Planet',
      movieReleaseYear: 1984,
      genre: [ 'Comedy' , 'Satire' , 'Sci-Fi'] ,
      rating: 'R',
      runtime: '1hr 48m',
      director: [ 'John Sayles' ],
      writer: [ 'John Sayles' ],
      cast: [ 'Joe Morton' , 'Steve James' , 'Bill Cobbs' , 'David Strathairn' ],
      accolades: [ 'Sitges - Catalonian International Film Festival' , 'Sundance Film Festival Winner' ],
      releaseDate: new Date('09/07/1984'),
      tags: [ 'artsy' , 'commentary' , 'artsy' , 'cult classic' , 'cool' ], 
      viewingNumber: 23,
      dateViewed: new Date('03/18/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Woman in Gold',
      movieReleaseYear: 2015,
      genre: [ 'Drama' , 'War' , 'Biography' , 'History' ] ,
      rating: 'PG-13',
      runtime: '1hr 49m',
      director: [ 'Simon Curtis' ],
      writer: [ 'Alexi Kaye Campbell' , 'E. Randol Schoenberg' , 'Maria Altmann' ],
      cast: [ 'Helen Mirren' , 'Ryan Reynolds' , 'Daniel Brühl' , 'Katie Holmes' , 'Tatiana Maslany' , 'Max Irons' , 'Charles Dance' , 'Elizabeth McGovern' , 'Jonathan Pyrce' ],
      accolades: [ 'Screen Actors Guild Nominee' , 'Cinema for Peace Awards Nominee' , 'Jupiter Award Nominee' , 'AARP Nominee'], 
      releaseDate: new Date('04/01/2015'),
      tags: [ 'political' , 'interesting' , 'Holocaust' , 'WWII' , 'about art' , 'sad' , 'underrated' ],
      viewingNumber: 24,
      dateViewed: new Date('03/20/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'No Way to Treat a Lady',
      movieReleaseYear: 1968,
      genre: [ 'Comedy', 'Dark Comedy' , 'Thriller', 'Crime' , 'Mystery' ] ,
      rating: 'Not Rated',
      runtime: '1hr 48m',
      director: [ 'Jack Smight' ],
      writer: [ 'John Gay' , 'William Goldman' ],
      cast: [ 'George Segal' , 'Rod Steiger' , 'Lee Remick' , 'Eileen Heckart' , 'Murray Hamilton' , 'Michael Dunn' , 'Martine Bartlett' ],
      accolades: [ 'BAFTA Nominee' , 'Sant Jordi Winner' ],
      releaseDate: new Date('03/20/1968'),
      tags: [ 'rip viewing' , 'cool' , 'underrated' , 'based on a book' ], 
      viewingNumber: 25,
      dateViewed: new Date('03/20/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Raising Arizona',
      movieReleaseYear: 1987,
      genre: [ 'Comedy' , 'Crime' , 'Slapstick' , 'Caper' ] ,
      rating: 'PG-13',
      runtime: '1hr 34m',
      director: [ 'Joel Coen' ],
      writer: [ 'Joel Coen' , 'Ethan Coen' ],
      cast: [ 'Nicolas Cage' , 'Holly Hunter' , 'Francis McDormand' , 'John Goodman' , 'Trey Wilson' , 'William Forsythe' , 'Sam McMurray' , 'Randall \'Tex\' Cobb' ],
      accolades: [ 'American Comedy Awards Nominee' , 'National Society of Film Critics Awars Nominee' , 'Young Artist Awards Nominee' ],
      releaseDate: new Date('03/18/1987'),
      tags: [ 'funny' , 'fun' , 'laugh out loud' , 'quirky' , 'cult classic' , 'silly' ], 
      viewingNumber: 26,
      dateViewed: new Date('04/01/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Enchanted April',
      movieReleaseYear: 1991,
      genre: [ 'Comedy' , 'Drama' ],
      rating: 'PG',
      runtime: '1hr 38m',
      director: [ 'Mike Newell' ],
      writer: [ 'Peter Barnes' ],
      cast: [ 'Miranda Richarson' , 'Josie Lawrence' , 'Polly Walker' , 'Joan Plowright' , 'Alfred Molina' , 'Michael Kitchen' , 'Jim Briadbent' ],
      accolades: [ 'Oscar Nominee' , 'Golden Globe Winner' , 'New York Film Circle Awards Winner' ],
      releaseDate: new Date('11/06/1991'),
      tags: [ 'gentle' , 'italian countryside' , 'travel' , 'period drama' , 'human condition' ], 
      viewingNumber: 27,
      dateViewed: new Date('04/16/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Romy and Michele\’s High School Union',
      movieReleaseYear: 1997,
      genre: [ 'Comedy' ] ,
      rating: 'R',
      runtime: '1hr 32m',
      director: [ 'David Mirkin' ],
      writer: [ 'Robin Schiff' ],
      cast: [ 'Mira Sorvino' , 'Lisa Kudrow' , 'Janeane Garofalo' , 'Alan Cumming' , 'Julia Campbell' , 'Mia Cottet' ],
      accolades: [ 'Satellite Awards Nominee' , 'MTV Movie + TV Awards Nominee' , 'Chlotrudis Awards Nominee' , '20/20 Awards Nominee' ],
      releaseDate: new Date('04/25/1997'),
      tags: [ 'buddy comedy' , 'screwball comedy' , 'quirky' , 'cult classic' , 'iconic' , 'gay cinema' , 'fun' , 'funny' , 'silly' , 'fashion in film' ], 
      viewingNumber: 28,
      dateViewed: new Date('04/22/2021'),
      picker: 'JuliaFleck',
      attendees: [ 'JuliaFleck', 'ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Trixie Mattel: Moving Parts',
      movieReleaseYear: 2019,
      genre: [ 'Documentary' , 'Drama' , 'Musical' ] ,
      rating: 'Not Rated',
      runtime: '1hr 31m',
      director: [ 'Nick Zeig-Owens' ],
      writer: [ ],
      cast: [ 'Trixie Mattel' , 'Benjamin Putnam' , 'Caldwell Tidicue' , 'Jaymes Mansfield' , 'Jinx Monsoon' , 'Katya Zamolodchikova' , 'Kennedy Davenport' , 'Latrice Royale' , 'RuPaul' ],
      accolades: [ 'WOWIE Awards Winner' , 'Queerty Awards Winner' ],
      releaseDate: new Date('04/25/2019'),
      tags: [ 'drag queens' , 'tribeca film festival' , 'gay cinema' , 'about music' , 'drugs' , 'recovery' , 'buddy movie' , 'indie' ],
      viewingNumber: 29,
      dateViewed: new Date('04/29/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'JuliaFleck' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Strictly Ballroom',
      movieReleaseYear: 1992,
      genre: [ 'Drama' ] ,
      rating: 'PG',
      runtime: '1hr 34m',
      director: [ 'Baz Luhrmann' ],
      writer: [ 'Baz Luhrmann' , 'Craig Pearce' , 'Andrew Bovell' ],
      cast: [ 'Paul Mercurio' , 'Tara Morice' , 'Bill Hunter' , 'Pat Thompson' , 'Gia Carides' , 'Peter Whitford' , 'Barry Otto' ],
      accolades: [ 'Cannes Film Festival Winner' , 'Australian Film Institute Awards Winner' , 'Golden Globe Nominee' ],
      releaseDate: new Date('08/20/1992'),
      tags: [ 'Australian' , 'indie' , 'low-budget' , 'dancing' , 'competition' , 'based on a play' , 'directorial debut' ],
      viewingNumber: 30,
      dateViewed: new Date('05/06/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'JohnCecilPrice', 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Promising Young Woman',
      movieReleaseYear: 2020,
      genre: [ 'Crime' , 'Drama' , 'Mystery' , 'Psychological Thriller' , 'Thriller' , 'Dark Comedy' , 'Comedy' ] ,
      rating: 'R',
      runtime: '1hr 53m',
      director: [ 'Emerald Fennell' ],
      writer: [ 'Emerald Fennell' ],
      cast: [ 'Carey Mulligan ' , 'Adam Brody' , 'Ray Nicholson' , 'Sam Richardson' , 'Timothy Goodwin' , 'Clancy Brown' , 'Jennifer Collidge' , 'Laverne Cox' , 'Alli Hart' , 'Alison Brie' , 'Christopger Mintz-Plasse' ] ,
      accolades: [ 'Oscar Winner' , 'BAFTA Winner' , 'Critics Choice Winner' ],
      releaseDate: new Date('01/25/2020'),
      tags: [ 'Sundance' , 'revenge' , 'strong female lead' , 'commentary' , 'twisted' , 'political' , 'creepy' ], 
      viewingNumber: 31,
      dateViewed: new Date('05/20/2021'),
      picker: 'ReynaHowkins',
      attendees: ['ReynaHowkins', 'AmyUnoShafer', 'DianaD\'Orazio', 'JohnCecilPrice'],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Charade',
      movieReleaseYear: 1963,
      genre: [ 'Comedy' , 'Mystery' , 'Thriller' , 'Romantic Comedy' , 'Romance' , 'Cozy Mystery' , 'Crime'] ,
      rating: 'Approved',
      runtime: '1hr 53m',
      director: [ 'Stanley Donen' ],
      writer: [ 'Peter Stone' , 'Marc Behn' ],
      cast: [ 'Audrey Hepburn' , 'Cary Grant' , 'Walter Matthau' , 'James Coburn' , 'George Kennedy' , 'Dominique Minot' , 'Ned Glass' , 'Jacques Marin' , 'Paul Bonifas' , 'Thomas Chelimsky'  ],
      accolades: [ 'Oscar Nominee' , 'BAFTA Winner' , 'Golden Globe ' ],
      releaseDate: new Date('12/05/1963'),
      tags: [ 'charming' , 'witty' , 'twisty' , 'cool' , 'classic' , 'fun' , 'funny' , 'intriguing' , 'fashion in film' ],
      viewingNumber: 32,
      dateViewed: new Date('06/10/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
          {
      movieTitle: 'City Slickers',
      movieReleaseYear: 1991,
      genre: [ 'Comedy' , 'Western' ] ,
      rating: 'PG-13',
      runtime: '1hr 53m',
      director: [ 'Ron Underwood' ],
      writer: [ 'Lowell Ganz' , 'Babaloo Mandel' ],
      cast: [ 'Billy Crystal' , 'Daniel Stern' , 'Bruno Kirby' , 'Patricia Wettig' , 'Helen Slater' , 'Jack Palance' , 'Noble Willingham' , 'Tracey Walter' , 'Josh Mostel' , 'David Paymer' ,  'Bill Henderson' , 'Jeffrey Tambor' , 'Yeardley Smith' , 'Jake Gyllenhaal' , 'Lindsay Crystal' ],
      accolades: [ 'Oscar Winner' , 'Genesis Awards Winner' , 'Golden Globe Winner' , 'MTV Movie Award Winner' , 'People\'s Choice Award Winner' ],
      releaseDate: new Date('06/07/1991'),
      tags: [ 'funny' , 'fun' , 'buddy movie' , 'cool' , 'classic' , 'touching' , 'laugh out loud' , 'different' ],
      viewingNumber: 33,
      dateViewed: new Date('06/24/2021'),
      picker: 'ErikKirby',
      attendees: [ 'ErikKirby', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Desperately Seeking Susan',
      movieReleaseYear: 1985,
      genre: [ 'Comedy' , 'Screwball Comedy' , 'Thriller' , 'Drama' ] ,
      rating: 'PG-13',
      runtime: '1hr 44m',
      director: [ 'Susan Seidelman' ],
      writer: [ 'Leora Barish' ],
      cast: [ 'Madonna' , 'Rosanna Arquette' , 'Aidan Quinn' , 'Robert Joy' , 'John Turturro' , 'Laurie Metcalf' ],
      accolades: [ 'National Film Registry' , 'BAFTA Winner' , 'Cannes Film Festival Nominee' , 'Golden Globe Nominee' ],
      releaseDate: new Date('04/12/1985'),
      tags: [ 'mistaken identities' , 'quirkly' , 'cult classic' , 'fashion in film' ], 
      viewingNumber: 34,
      dateViewed: new Date('07/01/2021'),
      picker: 'JohnCecilPrice',
      attendees: [ 'JohnCecilPrice', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The House Bunny',
      movieReleaseYear: 2008,
      genre: [ 'Comedy' , 'Romance' ] ,
      rating: 'PG-13',
      runtime: '1hr 38m',
      director: [ 'Fred Wolf' ],
      writer: [ 'Karen McCullah' , 'Kirsten Smith' ],
      cast: [ 'Anna Faris' , 'Colin Hanks' , 'Emma Stone' , 'Kat Dennings' , 'Katharine McPhee' , 'Rumer Willis' ],
      accolades: [ 'MTV Movie Awards Nominee' ],
      releaseDate: new Date('08/22/2008'),
      tags: [ 'mistaken identities' , 'quirkly' , 'cult classic' , 'fashion in film' ], 
      viewingNumber: 35,
      dateViewed: new Date('07/08/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'ReynaHowkins', 'AmyUnoShafer',  'JohnCecilPrice' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Private Benjamin',
      movieReleaseYear: 1980,
      genre: [ 'Comedy' , 'Satire' , 'War' ] ,
      rating: 'R',
      runtime: '1hr 49m',
      director: [ 'Howard Zieff' ],
      writer: [ 'Nancy Myers' , 'Charles Shyer' , 'Harvey Miller' ],
      cast: [ 'Goldie Hawn' , 'Eileen Brennan' , 'Armand Assante' , 'Robert Webber' , 'Sam Wanamaker' , 'Barbara Barrie' , 'Mary Kay Place' , 'Harry Dean Stanton' , 'Albert Brooks' ],
      accolades: [ 'Oscar Nominee' , 'Golden Globe Nominee' , 'Writers Guild of America Winner' ],
      releaseDate: new Date('10/10/1980'),
      tags: [ 'feminism in film' , 'interesting' , 'funny' , 'different' , 'commentary' ], 
      viewingNumber: 36,
      dateViewed: new Date('07/08/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Princess Bride',
      movieReleaseYear: 1987,
      genre: [ 'Comedy' , 'Adventure' , 'Family' , 'Fairy Tale' , 'Romance' , 'Swashbuckler' ] ,
      rating: 'PG',
      runtime: '1hr 38m',
      director: [ 'Rob Reiner' ],
      writer: [ 'William Goldman' ],
      cast: [ 'Cary Elwes' , 'Robin Wright' , 'Chris Sarandon' , 'Christopher Guest' , 'Wallace Shawn' , 'Mandy Patinkin' , 'André the Giant' , 'Billy Crystal' , 'Carol Kane' , 'Fred Savage' , 'Peter Falk' ],
      accolades: [ 'National Film Registry' , 'Oscar Nominee' , 'Grammy Nominee' , 'Hugo Winner' , 'Toronta International Film Festival Winner' ],
      releaseDate: new Date('09/25/1987'),
      tags: [ 'classic' , 'iconic' , 'creative' , 'funny' , 'fun' , 'cute' , 'touching' , 'sweet' , 'quirky' , 'perfection' , 'must-see' ],
      viewingNumber: 37,
      dateViewed: new Date('07/22/2021'),
      picker: 'LaurenGervasio',
      attendees: [ 'LaurenGervasio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Muriel\'s Wedding',
      movieReleaseYear: 1994,
      genre: [ 'Comedy' , 'Drama' , 'Romance' ] ,
      rating: 'R',
      runtime: '1hr 46m',
      director: [ 'P.J. Hogan' ],
      writer: [ 'P.J. Hogan' ],
      cast: [ 'Toni Collette' , 'Rachel Griffiths' , 'Bill Hunter' , '' ],
      accolades: [ 'BAFTA Nominee' , 'Film Critics Circle of Australian Awards' , 'Australian Film Institute Winner' , 'Cannes Film Festival Nominee' , 'Golden Globes Nominee' , 'Writers Guild of America Nominee' ],
      releaseDate: new Date('09/29/1994'),
      tags: [ 'buddy movie' , 'touching' , 'funny' , 'fun' , 'sad' , 'misfits' , 'australian' , 'low-budget' , 'indie' , 'iconic' , 'different' , 'quirky' ], 
      viewingNumber: 38,
      dateViewed: new Date('08/12/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Only Lovers Left Alive',
      movieReleaseYear: 2013,
      genre: [ 'Fantasy', 'Horror' , 'Comedy' , 'Romance' , 'Drama' ] ,
      rating: 'R',
      runtime: '2hr 3m',
      director: [ 'Jim Jarmusch' ],
      writer: [ 'Jim Jarmusch' , 'Marion Bessay' ],
      cast: [ 'Tilda Swinton' , 'Tom Hiddleston' , 'Mia Wasikowska' , 'Anton Yelchin' , 'Jeffrey Wright' , 'Slimane Dazi' , 'Jhn Hurt' , 'Carter Logan' ],
      accolades: [ 'Cannes Film Festival Winner' , 'Vancouver Film Critics Circle Winner' , 'SXSW Film Festival Nominee' ],
      releaseDate: new Date('05/25/2013'),
      tags: [ 'vampires' , 'surreal' , 'cool' ],
      viewingNumber: 39,
      dateViewed: new Date('08/19/2021'),
      picker: 'BeckySwinton',
      attendees: [ 'BeckySwinton' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Clue',
      movieReleaseYear: 1985,
      genre: [ 'Comedy' , 'Crime' , 'Mystery' , 'Farce' , 'Whodunit' , 'Slapstick' ] ,
      rating: 'PG',
      runtime: '1hr 37m',
      director: [ 'Jonathan Lynn' ],
      writer: [ 'John Landis' , 'Jonathan Lynn' , 'Anthony E. Pratt' ],
      cast: [ 'Tim Curry' , 'Eileen Brennan' , 'Madeline Kahn' , 'Christopher Lloyd' , 'Michael McKean' , 'Martin Mull' , 'Lesley Ann Warren' , 'Colleen Camp' , 'Lee Ving' , 'Bill Henderson' , 'Jane Wiedlin' , 'Jeffrey Kramer' , 'Kellye Nakahara' ],
      accolades: [ ],
      releaseDate: new Date('12/13/1985'),
      tags: [ 'funny' , 'fun' , 'different' , 'classic' , 'cult classic' , 'based on a game' , 'quirky' , 'dark' , 'silly' ],
      viewingNumber: 40,
      dateViewed: new Date('08/26/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Shining',
      movieReleaseYear: 1980,
      genre:  [ 'Horror' , 'Drama' , 'Psychological Horror' ] ,
      rating: 'R',
      runtime: '2hr 26m',
      director: [ 'Stanley Kubrick' ],
      writer: [ 'Stanely Kubrick' , 'Diane Johnson' ],
      cast: [ 'Jack Nicholson' , 'Shelley Duvall' , 'Scatman Crothers' , 'Danny Llyoyd' , 'Joe Turkel' ],
      accolades: [ 'National Film Registry' ],
      releaseDate: new Date('05/23/1980'),
      tags: [ 'classic' , 'must-see' , 'artsy' , 'creepy' , 'haunted' ],
      viewingNumber: 41,
      dateViewed: new Date('09/02/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Hair Love',
      movieReleaseYear: 2019,
      genre: [ 'Short Film', 'Animation' , 'Comedy' ] ,
      rating: 'G',
      runtime: '7m',
      director: [ 'Matthew A. Cherry' , 'Everett Downing Jr.' , 'Bruce W. Smith' ],
      writer: [ 'Maathew A. Cherry' ],
      cast: [ 'Issa Rae' ],
      accolades: [ 'Oscar Winner' , 'Black Reel Awards Winner' ],
      releaseDate: new Date('08/14/2019'),
      tags: [ 'cute' , 'gentle' , 'commentary' , 'about family' ],
      viewingNumber: 42,
      dateViewed: new Date('09/10/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Two Distant Strangers',
      movieReleaseYear: 2020,
      genre: [ 'Short Film' ] ,
      rating: 'Not Rated',
      runtime: '32m',
      director: [ 'Travon Free' , 'Martin Desmond' ],
      writer: [ 'Travon Free' ],
      cast: [ 'Joey Badass' , 'Andrew Howard' , 'Zaria Simone' ],
      accolades: [ 'Oscar Winner' , 'African-American Film Critics Association Winner' ],
      releaseDate: new Date('11/20/2020'),
      tags: [ 'sad' , 'interesting' , 'creative' , 'twisty' ],
      viewingNumber: 42,
      dateViewed: new Date('09/10/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Office Space',
      movieReleaseYear: 1999,
      genre: [ 'Comedy' , 'Satire' ] ,
      rating: 'R',
      runtime: '1 hr 29m',
      director: [ 'Mike Judge' ],
      writer: [ 'Mike Judge' ],
      cast: [ 'Ron Livingston' , 'Jennifer Aniston' , 'David Herman' , 'Ajay Naidu' , 'Diedrich Bader' , 'Stephen Root' , 'Gary Cole' , 'Richard Riehle' , 'Alexandra Wentworth' , 'Joe Bays' ],
      accolades: [ ], 
      tags: [ 'cult classic' , 'funny' , 'fun' , 'workplace comedy' ] ,
      releaseDate: new Date('02/19/1999') , 
      viewingNumber: 43,
      dateViewed: new Date('09/16/2021'),
      picker: 'ErikEvans',
      attendees: [ 'ErikEvans', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Screwed',
      movieReleaseYear: 2000,
      genre: [ 'Comedy' ] ,
      rating: 'PG-13',
      runtime: '1hr 22m',
      director: [ 'Scott Alexander' , 'Larry Karaszewski' ],
      writer: ['Scott Alexander' , 'Larry Karaszewski' ],
      cast: [ 'Norm Macdonald' , 'Dave Chappelle' , 'Elaine Stritch' , 'Daniel Benzali' , 'Sherman Hemsley' , 'Danny DeVito' , 'Sarah Silverman' ],
      accolades: [ ],
      releaseDate: new Date('05/20/2000'),
      tags: [ 'rip viewing' , 'buddy movie' ], 
      viewingNumber: 44,
      dateViewed: new Date('09/22/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Baby Mama',
      movieReleaseYear: 2008,
      genre: [ 'Comedy' , 'Romance' ] ,
      rating: 'PG-13',
      runtime: '1hr 39m',
      director: [ 'Michael McCullers' ],
      writer: [ 'Michael McCullers' ],
      cast: [ 'Tina Fey' , 'Amy Poehler' , 'Greg Kinnear' , 'Dax Shepard' , 'Romany Malco' , 'Maura Tierney' , 'Holland Taylor' , 'Sigourney Weaver' ],
      accolades: [ 'MTV Movie Award Winner' , 'People\'s Choice Awards Nominee' , 'Teen Choice Awards Nominee' ],
      releaseDate: new Date('04/25/2008'),
      tags: [ 'funny' , 'fun' , 'buddy movie' , 'laugh out loud' , 'underrated' ],
      viewingNumber: 45,
      dateViewed: new Date('09/29/2021'),
      picker: 'LaurenGervasio',
      attendees: [ 'LaurenGervasio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Arsenic and Old Lace',
      movieReleaseYear: 1944,
      genre: [ 'Comedy' , 'Crime' , 'Dark Comedy' , 'Farce' , 'Thriller' , 'Screwball Comedy' ] ,
      rating: 'Not Rated',
      runtime: '1hr 58m',
      director: [ 'Frank Capra' ],
      writer: [ 'Julius J. Epstein' , 'Philip G. Epstein' , 'Joseph Kesselring' ],
      cast: [ 'Cary Grant' , 'Raymond Massey' , 'Priscilla Lane' , 
        'Peter Lorre' , 'Edward Everett Horton' , 'James Gleason' , 'Josephine Hull' , 'Jean Adair' , 'John Alexandar' ],
      accolades: [ 'National Film Registry' , 'Photoplay Awards Winner' ],
      releaseDate: newDate('09/01/1944') ,
      tags: [ 'classic' , 'halloween' , 'funny' , 'dark' , 'black and white' ],
      viewingNumber: 46,
      dateViewed: new Date('10/06/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Edward Scissorhands',
      movieReleaseYear: 1990,
      genre: [ 'Comedy' , 'Fanstasy' , 'Drama' , 'Romance' ] ,
      rating: 'PG-13',
      runtime: '1hr 45m',
      director: [ 'Tim Burton' ],
      writer: [ 'Caroline Thompson' ],
      cast: [ 'Johnny Depp' , 'Winona Ryder' , 'Dianne West' , 'Anthony Michael Hall' , 'Kathy Baker' , 'Vincent Price' , 'Alan Arkin' ],
      accolades: [ 'Oscar Nominee' , 'BAFTA Winner' , 'Golden Globe Nominee' , 'Hugo Award Winner' , 'Grammy Nominee' ],
      releaseDate: new Date('12/07/1990'),
      tags: [ 'classic' , 'gothic' , 'misfits' , 'sad' , 'bittersweet' , 'funny' , 'different' , 'stylistic' ],
      viewingNumber: 47,
      dateViewed: new Date('10/13/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'What We Do In Shadows',
      movieReleaseYear: 2014,
      genre: ['Comedy', 'Mockumentary' , 'Horror' , 'Dark Comedy' , 'Satire' ] ,
      rating: 'R',
      runtime: '1hr 26m',
      director: [ 'Jemaine Clement' , 'Taika Waititi' ],
      writer: [ 'Jemaine Clement' , 'Taika Waititi' ],
      cast: [ 'Jemaine Clement' , 'Taika Waititi' , 'Jonny Brugh' , 'Cori Gonzalez-Macuer' , 'Stu Rutherford' , 'Ben Fransham' , 'Jackie van Beek' , 'Elena Stejko' , 'Rhys Darby' ],
      accolades: [ 'Saturn Awards Nominee' , 'Sitges Winner' , 'Hawaii Internaional Film Festival Winner' , 'New Zealand Screen Awards Winner' ],
      releaseDate: new Date('01/19/2014'),
      tags: [ 'vampires' , 'halloween' , 'low-budget' , 'indie' , 'funny' , 'fun' , 'laugh out loud' , 'crowdfunded' , 'new zealand' , 'cult classic' ],
      viewingNumber: 48, 
      dateViewed: new Date('10/20/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'DianaD\'Orazio', 'AmyUnoShafer', 'ReynaHowkins' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Young Frankenstein',
      movieReleaseYear: 1974,
      genre: [ 'Comedy', 'Parody' , 'Farce' , 'Slapstick' ] ,
      rating: 'PG',
      runtime: '1hr 46m',
      director: [ 'Mel Brooks' ],
      writer: [ 'Mel Brooks' , 'Gene Wilder' , 'Mary Shelley' ],
      cast: [ 'Gene Wilder' , 'Teri Garr' , 'Marty Feldman' , 'Madeline Kahn' , 'Peter Boyle' , 'Cloris Leachman' , 'Kenneth Mars' ],
      accolades: [ 'Oscar Nominee' , 'Golden Globe Nominee' , 'Hugo Awards Winner' , 'National Film Registry' ],
      releaseDate: new Date('12/15/1974'),
      tags: [ 'classic' , 'must-see' , 'iconic' , 'funny' , 'fun' , 'laugh out loud' , 'zany' , 'black and white' ],
      viewingNumber: 49,
      dateViewed: new Date('10/27/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Labyrinth',
      movieReleaseYear: 1986,
      genre:  [ 'Fantasy' , 'Family' , 'Musical' , 'Adventure' ] ,
      rating: 'PG',
      runtime: '1hr 46m',
      director: [ 'Jim Henson' ],
      writer: [ 'Terry Jones' ],
      cast: [ 'Jennifer Connelly' , 'David Bowie' ],
      accolades: [ ],
      releaseDate: new Date('06/27/1986'),
      tags: [ 'classic' , 'cult classic' , 'amazing soundtrack' , 'creative' , 'dazzling' , 'dreamlike' , 'fun' ],
      viewingNumber: 50,
      dateViewed: new Date('11/03/2021'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'American Graffiti',
      movieReleaseYear: 1973,
      genre:  [ 'Comedy' , 'Teen Comedy' , 'Coming-of-Age' , 'Drama' ] ,
      rating: 'PG',
      runtime: '1hr 50m',
      director: [ 'George Lucas' ],
      writer: [ 'George Lucas' , 'Gloria Katz' , 'Willard Huyck' ],
      cast: [ 'Richard Dreyfuss' , 'Ron Howard' , 'Paul Le Mat' , 'Harrison Ford' , 'Charles Martin Smith' , 'Cindy Williams' , 'Candy Clark' , 'Mackenzie Phillips' , 'Wolfman Jack' , 'Lynne Marie Stewart' , 'Bo Hopkins' ],
      accolades: [ 'Oscar Nominee' , 'BAFTA Nominee' , 'Directors Guild of America Nominee' , 'Golden Globe Winner' , 'National Film Registry' ],
      releaseDate: new Date('08/11/1973'),
      tags: [ 'slice-of-life' , 'amazing soundtrack' , 'cool' , 'one-night adventures' , 'vignettes' ],
      viewingNumber: 51,
      dateViewed: new Date('11/09/2021'),
      picker: 'ErikKirby',
      attendees: [ 'ErikKirby', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },  
     {
      movieTitle: 'The Greatest Showman',
      movieReleaseYear: 2017,
      genre: [ 'Musical' , 'Biography' , 'Drama' ] ,
      rating: 'PG',
      runtime: '1hr 45m',
      director: [ 'Michael Gracey' ],
      writer: [ 'Jenny Bicks' , 'Bill Condon' ],
      cast: [ 'Hugh Jackman' , 'Michelle Williams' , 'Zac Efron' , 'Zendaya' , 'Rebecca Ferguson' , 'Keala Settle' , 'Austyn Johnson' , 'Cameron Seely' , 'Sam Humphrey' ],
      accolades: [ 'Ocsar Nominee' , 'Saturn Award Winner' , 'Golden Globe Winner' , 'Grammy Winner' ],
      releaseDate: new Date('12/20/2017'),
      tags: [ 'based on a true story' , 'showbiz' , 'period drama' , 'song and dance' , 'glossy' ], 
      viewingNumber: 52,
      dateViewed: new Date('11/17/2021'),
      picker: 'LaurenGervasio',
      attendees: [ 'LaurenGervasio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },  
     {
      movieTitle: 'The Adventures of Baron Munchausen',
      movieReleaseYear: 1988,
      genre:  [ 'Adventure' , 'Fantasy' , 'Family' , 'Comedy' , 'Epic' , 'Dark Comedy' ] ,
      rating: 'PG',
      runtime: '2hr 6m',
      director: [ 'Terry Gilliam' ],
      writer: [ 'Charles McKeown' , 'Terry Gilliam' ],
      cast: [ 'John Neville' , 'Eric Idle' , 'Sarah Polley' , 'Oliver Reed' , 'Uma Thurman' , 'Jonathan Pryce' , 'Valentina Cortese' ],
      accolades: [ 'Oscar Nominee' ,'Saturn Awards Nominee' , 'BAFTA Winner' ],
      releaseDate: new Date('03/10/1988'),
      tags: [ 'quirky' , 'dreamlike' , 'creative' , 'visual effects' , 'stylistic' , 'artsy' , 'quest' ],
      viewingNumber: 53,
      dateViewed: new Date('11/24/2021'),
      picker: 'RuthSchanbacher',
      attendees: [ 'RuthSchanbacher', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Die Hard',
      movieReleaseYear: 1988,
      genre:  [ 'Action' , 'Thriller' ] ,
      rating: 'R',
      runtime: '2hr 11m',
      director: [ 'John McTiernan' ],
      writer: [ 'Jeb Stuart' , 'Steven E. de Souza' ],
      cast: [ 'Bruce Willis' , 'Alan Rickman' , 'Alexander Godunov' , 'Bonnie Bedelia' , 'Reginald VelJohnson' ],
      accolades: [ 'Oscar Nominee' , 'Awards of Japanese Academy Winner' , 'National Film Registry' ],
      releaseDate: new Date('07/15/1988'),
      tags: [ 'iconic' , 'quotable' , 'fun' , 'funny' , 'franchise' , 'holiday' , 'one-person army' , 'franchise' , 'based on a book' ],
      viewingNumber: 54,
      dateViewed: new Date('12/01/2021'),
      picker: 'LaurenEvans',
      attendees: [ 'LaurenEvans', 'AmyUnoShafer' , 'RuthSchanbacher' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'The Accidental Tourist',
      movieReleaseYear: 1988,
      genre:  [ 'Romance' , 'Drama' , 'Comedy' ] ,
      rating: 'PG',
      runtime: '2hr 1m',
      director: [ 'Lawrence Kasdan' ],
      writer: [ 'Frank Galati' , 'Lawrence Kasdan' , 'Anne Tyler' ],
      cast: [ 'Geena Davis' , 'William Hurt' , 'Kathleen Turner' ],
      accolades: [ 'Oscar Winner' , 'New York Film Critics Circle Awards Winner' , 'Golden Globe Nominee' , 'BAFTA Nominee' ],
      releaseDate: new Date('12/23/1988'),
      tags: [ 'based on a book' , 'quirky' , 'rom-com' , 'touching' , 'heavy' ], 
      viewingNumber: 55,
      dateViewed: new Date('12/15/2021'),
      picker: 'DianaD\'Orazio',
      attendees: [ 'DianaD\'Orazio', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },
     {
      movieTitle: 'Clueless',
      movieReleaseYear: 1995,
      genre:  [ 'Comedy' , 'Romance' , 'Rom-Com' ,'Coming-of-Age' ] ,
      rating: 'PG-13',
      runtime: '1hr 37m',
      director: [ 'Amy Heckerling'],
      writer: [ 'Amy Heckerling' ],
      cast: [ 'Alicia Silverstone' , 'Stacey Dash' , 'Brittany Murphy' , 'Paul Rudd' , 'Donald Faison' , 'Elisa Donovan' , 'Breckin Meyer' , 'Jeremy Sito' , 'Dan Hedaya' , 'Wallace Shawn' , 'Twink Caplan' ],
      accolades: [ 'American Comedy Awards Winner' , 'Blockbuster Enterntainment Awards Winner' , 'Kids\' Choice Awards Nominee' , 'MTV Movie Awards Winner' , 'New York Film Critics Circle Awards Nominee' , 'National Board of Review Winner' ],
      releaseDate: new Date('07/19/1995'),
      tags: [ 'classic' , 'cute' , 'iconic' , 'quotable' , 'based on a book' , 'modern takes' , 'lady director' ], 
      viewingNumber: 56,
      dateViewed: new Date('12/22/2021'),
      picker: 'ReynaHowkins',
      attendees: [ 'ReynaHowkins', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     }, 
     {
      movieTitle: 'Silver Streak',
      movieReleaseYear: 1976,
      genre: [ 'Action' , 'Adventure' , 'Crime' , 'Comedy' , 'Romance' , 'Thriller' ] ,
      rating: 'PG',
      runtime: '1hr 54m',
      director: [ 'Arthur Hiller' ],
      writer: [ 'Colin Higgins' ],
      cast: [ 'Gene Wilder' , 'Richard Pryor' , 'Jill Clayburgh' ],
      accolades: [ 'Oscar Nominee' , 'Golden Globe Nominee'], 
      releaseDate: new Date('12/08/1976') , 
      tags: [ 'mistaken identity' , 'cult classic' , 'comedy duo' ] ,
      viewingNumber: 57,
      dateViewed: new Date('12/29/2021'),
      picker: 'AmyUnoShafer',
      attendees: [ 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 2'
     },   
     // Season 3
     {
      movieTitle: 'Tootsie',
      movieReleaseYear: 1982,
      genre: [ 'Comedy', 'Romance' ] ,
      rating: 'PG',
      runtime: '1h 56m',
      director: [ 'Sydney Pollack' ],
      writer: [ 'Larry Gelbart' , 'Murray Schisgal' ],
      cast: [ 'Dustin Hoffman' , 'Jessica Lange' , 'Teri Garr' , 'Dabney Coleman' , 'Charles Durning' , 'Geena Davis' , 'Bill Murray' ],
      accolades: [ 'Oscar Winner' , 'National Film Registry' , 'American Film Institute Inductee'], 
      releaseDate: newDate('12/17/1982') , 
      tags: [ 'feminism' , 'gender roles' , 'drag' , 'showbiz' , 'soap opera' , 'love triangle' , 'classic' , 'social commentary' ] ,
      releaseDate: new Date('12/17/1982'),
      viewingNumber: 58,
      dateViewed: new Date('01/05/2022'),
      picker: 'DawnFallik',
      attendees: [ 'DawnFallik', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 3'
     },  
     {
      movieTitle: 'Scott Pilgrim vs the World',
      movieReleaseYear: 2010,
      genre: [ 'Comedy', 'Action' ] ,
      rating: 'PG-13',
      runtime: '1h 52m',
      director: [ 'Edgar Wright' ],
      writer: [ 'Edgar Wright' , 'Michael Bacall' , 'Byran Lee O\'Malley' ],
      cast: [ 'Michael Cera' , 'Kieran Culkin' , 'Anna Kendrick' , 'Alison Pill' , 'Aubrey Plaza' , 'Mary Elizabeth Winstead' , 'Jason Schwartzman' , 'Ellen Wong' , 'Chris Evans' , 'Brie Lawson' , 'Mae Whitman' , 'Bill Hader'],
      accolades: [ 'Lund International Fantastic Film Festival' ], 
      releaseDate: new Date('08/13/2010'), 
      tags: [ 'indie' , 'toronto' , 'graphic novel' , 'visual effects' , 'quirky' , 'cult classics' , 'coming-of-age' ] ,
      viewingNumber: 59,
      dateViewed: new Date('01/12/2022'),
      picker: 'RuthSchanbacher',
      attendees: [ 'RuthSchanbacher', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 3'
     },  
     {
      movieTitle: 'Waking Ned Devine',
      movieReleaseYear: 1998,
      genre: [ 'Comedy', 'Indie' ] ,
      rating: 'PG',
      runtime: '1h 31m',
      director: [ 'Kirk Jones' ],
      writer: [ 'Kirk Jones' ],
      cast: [ 'Ian Bannen' , 'David Kelly' , 'Fionnula Flanagan' , 'Susan Lynch' , 'James Nesbitt'],
      accolades: [ 'BAFTA Nominee' ], 
      releaseDate: new Date('11/20/1998'), 
      tags: [ 'indie' , 'heartwarming' , 'buddy movie' , 'sweet' , 'irish' , 'cult classic' , 'underrated' ] ,
      viewingNumber: 60,
      dateViewed: new Date('01/19/2022'),
      picker: 'JenniferO\'Shea',
      attendees: [ 'JenniferO\'Shea', 'AmyUnoShafer' ],
      memberRating: null,
      currentlyStreaming: null,
      season: 'Season 3'
     },  
  ]);

  const merch = await db.merch.insertMany([
    // add your merch data here
  ]);

  console.log('Hit Play!');
}
